# Generated by Django 3.1.2 on 2021-11-10 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='castrado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=200, null=True, verbose_name='Energía'),
        ),
        migrations.AddField(
            model_name='post',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='post',
            name='energia',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=200, null=True, verbose_name='Energía'),
        ),
        migrations.AddField(
            model_name='post',
            name='sexo',
            field=models.CharField(choices=[('macho', 'macho'), ('hembra', 'hembra')], max_length=200, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='post',
            name='tamanio',
            field=models.CharField(choices=[('pequeño', 'pequeño'), ('mediano', 'mediano'), ('grande', 'grande')], max_length=200, null=True, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 2, 5, 29, 336102), verbose_name='Fecha de publicación'),
        ),
    ]
