# Generated by Django 3.1.2 on 2021-11-11 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20211110_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contacto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='refugio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='castrado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=200, null=True, verbose_name='castrado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 0, 19, 34, 671216), verbose_name='Fecha de publicación'),
        ),
    ]
