# Generated by Django 3.1.2 on 2021-11-11 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_auto_20211111_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterField(
            model_name='post',
            name='castrado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=200, null=True, verbose_name='Esterilizado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contacto',
            field=models.CharField(default='https://wa.me/59173091061', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 0, 50, 31, 737623), verbose_name='Fecha de publicación'),
        ),
    ]
