# Generated by Django 3.1.2 on 2021-11-11 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_auto_20211111_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.TextField(null=True, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 0, 52, 51, 59904), verbose_name='Fecha de publicación'),
        ),
    ]
